This file is to experiment with setting thresholds for our data with NLP-produced similarity scores
- for now, just using some sample file(s) from get_scores()
- sectioning off data by each .1 of similarity scores (.9-1.0, .8-.9, etc)
- then, get cohen's kappas on that for comparison

In [41]:
import pandas as pd
from NLP_Eval_for_DE import scores, data
import ast
from sklearn.metrics import cohen_kappa_score

In [ ]:
testable_data = data.get_testable_data("Example\\inputs\\case study 1 input\\pain points full.csv")
codes = data.get_codes("Example\\inputs\\case study 1 input\\short titles.csv")
all_scores = scores.get_Jina_scores(testable_data, codes)[1]

#split the lots of scores in the "Similarity scores" column into separate columns
all_scores_expanded = all_scores.copy()
all_scores_expanded[["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]] = pd.DataFrame(all_scores_expanded["Similarity scores"].tolist(), index=all_scores_expanded.index)
# add the "Consensus code" column of testable_data to all_scores_expanded
all_scores_expanded["Consensus code"] = testable_data["Consensus code"].tolist()
#delete the "Similarity scores" column
all_scores_expanded = all_scores_expanded.drop(columns=["Similarity scores"])
all_scores_expanded

,Input phrase,Similarity scores,1,2,3,4,5,6,7,8,9,10,11,Consensus code
0,cutting wood,"[0.65914696, 0.68691725, 0.6393915, 0.7534347,...",0.659147,0.686917,0.639391,0.753435,0.718065,0.797052,0.696077,0.789611,0.714689,0.691254,0.618896,0
1,didn�t know how to use lathe,"[0.7758371, 0.7071324, 0.5981057, 0.65807265, ...",0.775837,0.707132,0.598106,0.658073,0.673782,0.651082,0.650906,0.666729,0.711350,0.613773,0.586010,1
2,Finding drill,"[0.7039082, 0.82575095, 0.64815205, 0.6671239,...",0.703908,0.825751,0.648152,0.667124,0.709036,0.691553,0.717402,0.629175,0.824288,0.637896,0.636742,9
3,Taking out trash,"[0.61731094, 0.65654826, 0.639607, 0.63682663,...",0.617311,0.656548,0.639607,0.636827,0.704794,0.726124,0.715366,0.743981,0.678400,0.816364,0.599845,10
4,Finding clamp,"[0.698143, 0.67444193, 0.62876827, 0.6766978, ...",0.698143,0.674442,0.628768,0.676698,0.885455,0.673837,0.720935,0.655932,0.699091,0.689412,0.633356,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,Incorrect size gloves,"[0.6595968, 0.7382914, 0.8386486, 0.6418756, 0...",0.659597,0.738291,0.838649,0.641876,0.643478,0.623995,0.645385,0.623544,0.649213,0.657648,0.595388,3
395,Uncleaned machines from previous users,"[0.66961616, 0.6212497, 0.6044808, 0.6145736, ...",0.669616,0.621250,0.604481,0.614574,0.720937,0.663420,0.735110,0.704761,0.707858,0.674458,0.597780,6
396,Machine incorrectly set up by previous user,"[0.7067125, 0.67998904, 0.6040233, 0.641116, 0...",0.706712,0.679989,0.604023,0.641116,0.672666,0.636422,0.768434,0.632805,0.706544,0.647260,0.608389,1
397,Unusable wood scarps were discarded in wrong p...,"[0.68631643, 0.64990467, 0.59430903, 0.6379744...",0.686316,0.649905,0.594309,0.637974,0.740876,0.773018,0.660722,0.833772,0.704854,0.726929,0.623767,8
398,Trash bag was torn,"[0.67276335, 0.64441377, 0.6636173, 0.6302071,...",0.672763,0.644414,0.663617,0.630207,0.714648,0.692363,0.721005,0.706531,0.653639,0.947665,0.598647,10

In [76]:
# now filter based on threshold 
min = 0.9
max = 1.0
# drop any rows where the highest score from the 11 scores is not between min and max
all_scores_expanded_filtered = all_scores_expanded[(all_scores_expanded[["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]].max(axis=1) >= min) & (all_scores_expanded[["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]].max(axis=1) <= max)]
all_scores_expanded_filtered

,Input phrase,Similarity scores,1,2,3,4,5,6,7,8,9,10,11,Consensus code
23,lathe chuck tightened too tight,"[0.93225986, 0.7850034, 0.61355317, 0.6118187,...",0.932260,0.785003,0.613553,0.611819,0.710815,0.612184,0.624168,0.591448,0.694529,0.612434,0.620547,1
26,Finding clamps,"[0.6889468, 0.66507596, 0.623487, 0.66982204, ...",0.688947,0.665076,0.623487,0.669822,0.913072,0.678755,0.713313,0.677950,0.689193,0.674919,0.631177,5
31,Height of miter saw,"[0.58212316, 0.6182599, 0.57936734, 0.9281533,...",0.582123,0.618260,0.579367,0.928153,0.603224,0.678420,0.623901,0.606485,0.611006,0.576042,0.561073,4
33,Ripped Trash bag,"[0.6559895, 0.6101904, 0.6384808, 0.6411876, 0...",0.655990,0.610190,0.638481,0.641188,0.700307,0.696051,0.696083,0.727758,0.650865,1.000000,0.562800,10
43,She was bumped into,"[0.65827346, 0.66756225, 0.6125785, 0.68157375...",0.658273,0.667562,0.612579,0.681574,0.733103,0.702337,0.905657,0.629873,0.684305,0.706430,0.634523,7
57,Ripped trash bag,"[0.6559895, 0.6101904, 0.6384808, 0.6411876, 0...",0.655990,0.610190,0.638481,0.641188,0.700307,0.696051,0.696083,0.727758,0.650865,1.000000,0.562800,10
85,Someone bumped into her,"[0.6348177, 0.6499023, 0.6004541, 0.6723578, 0...",0.634818,0.649902,0.600454,0.672358,0.727994,0.703276,0.910152,0.628600,0.674638,0.699084,0.629565,7
86,Trash was ripped,"[0.6610016, 0.645005, 0.64369893, 0.64744973, ...",0.661002,0.645005,0.643699,0.647450,0.729360,0.697385,0.704337,0.759959,0.670853,0.929252,0.594642,10
90,Got bumped into,"[0.659939, 0.6740671, 0.6244695, 0.6828936, 0....",0.659939,0.674067,0.624470,0.682894,0.739855,0.720194,0.937652,0.655540,0.705832,0.724154,0.636733,7
95,Rip in trash bag,"[0.6765851, 0.6544485, 0.641317, 0.6397744, 0....",0.676585,0.654449,0.641317,0.639774,0.731274,0.721945,0.710640,0.735425,0.643936,0.931789,0.598167,10
103,ripped trash bag,"[0.6559895, 0.6101904, 0.6384808, 0.6411876, 0...",0.655990,0.610190,0.638481,0.641188,0.700307,0.696051,0.696083,0.727758,0.650865,1.000000,0.562800,10
108,ripped trash bag,"[0.6559895, 0.6101904, 0.6384808, 0.6411876, 0...",0.655990,0.610190,0.638481,0.641188,0.700307,0.696051,0.696083,0.727758,0.650865,1.000000,0.562800,10
117,Trash bag wripped,"[0.668961, 0.63508946, 0.67477745, 0.64196205,...",0.668961,0.635089,0.674777,0.641962,0.725211,0.708022,0.750593,0.716253,0.680087,0.924101,0.616390,10
122,Drill to big,"[0.7525107, 0.9441334, 0.7078518, 0.6771, 0.69...",0.752511,0.944133,0.707852,0.677100,0.697605,0.660689,0.670223,0.596024,0.763582,0.620577,0.631056,2
128,There was a rip in the trash bag,"[0.68178236, 0.6674957, 0.64109045, 0.64135015...",0.681782,0.667496,0.641090,0.641350,0.730589,0.722989,0.728454,0.734002,0.655338,0.918395,0.621563,10
135,The trash bag was ripped,"[0.6685262, 0.64567953, 0.6465071, 0.6486163, ...",0.668526,0.645680,0.646507,0.648616,0.723457,0.705949,0.720500,0.725881,0.659277,0.967932,0.595669,10
139,The lathe chuck was too tight,"[0.92262894, 0.80567324, 0.6320131, 0.6178589,...",0.922629,0.805673,0.632013,0.617859,0.722782,0.642445,0.616707,0.627042,0.699754,0.632085,0.628981,1
140,Drill was too big,"[0.7766088, 0.96934575, 0.6793074, 0.6611302, ...",0.776609,0.969346,0.679307,0.661130,0.692960,0.649276,0.653879,0.614647,0.767547,0.628186,0.628170,2
143,12v drill was in unlabeled cabinet,"[0.7069253, 0.77467966, 0.57966775, 0.65041506...",0.706925,0.774680,0.579668,0.650415,0.689838,0.666754,0.687014,0.633873,0.931711,0.621182,0.579497,9
153,The trash bag was ripped,"[0.6685262, 0.64567953, 0.6465071, 0.6486163, ...",0.668526,0.645680,0.646507,0.648616,0.723457,0.705949,0.720500,0.725881,0.659277,0.967932,0.595669,10
155,Someone bumped into him,"[0.6468597, 0.67074996, 0.62522304, 0.6867686,...",0.646860,0.670750,0.625223,0.686769,0.727069,0.717127,0.929344,0.643104,0.682424,0.708286,0.645045,7
157,Someone bumped into them,"[0.6520565, 0.6738698, 0.6412544, 0.6969223, 0...",0.652057,0.673870,0.641254,0.696922,0.767676,0.730871,0.912941,0.678485,0.698082,0.722443,0.660533,7
160,Garbage bag ripped,"[0.65321356, 0.61830807, 0.6417494, 0.6378683,...",0.653214,0.618308,0.641749,0.637868,0.698348,0.687357,0.696528,0.713777,0.646975,0.983451,0.574871,10
166,Torn garbage bag,"[0.6689164, 0.6298403, 0.6540709, 0.6250645, 0...",0.668916,0.629840,0.654071,0.625064,0.711051,0.688683,0.704993,0.703147,0.660683,0.957087,0.586045,10
172,Wrong size drill,"[0.7339333, 0.92430663, 0.6449704, 0.6693602, ...",0.733933,0.924307,0.644970,0.669360,0.652424,0.628110,0.641857,0.599230,0.786842,0.601912,0.593855,2
174,Trash can ripped,"[0.6476573, 0.6337609, 0.635345, 0.6536892, 0....",0.647657,0.633761,0.635345,0.653689,0.701878,0.681549,0.701272,0.720161,0.668079,0.932723,0.593208,10
175,Scraps of wood,"[0.6538922, 0.64098954, 0.64207894, 0.68125504...",0.653892,0.640990,0.642079,0.681255,0.764390,0.846412,0.695595,0.927557,0.714130,0.765189,0.615462,8
191,Trash bag was ripped,"[0.6731103, 0.64082545, 0.6540079, 0.6467726, ...",0.673110,0.640825,0.654008,0.646773,0.716365,0.695275,0.724760,0.721131,0.657216,0.974074,0.589199,10
197,The garbage bag was ripped.,"[0.6734819, 0.6494929, 0.6430055, 0.6424123, 0...",0.673482,0.649493,0.643005,0.642412,0.729493,0.712602,0.710494,0.725332,0.664040,0.953591,0.604349,10
199,The drill was too big.,"[0.7721653, 0.95074457, 0.6770271, 0.667009, 0...",0.772165,0.950745,0.677027,0.667009,0.691189,0.656178,0.645544,0.621818,0.749263,0.639714,0.629934,2
210,Miter saw too tall,"[0.6639894, 0.73999697, 0.62709254, 0.9361793,...",0.663989,0.739997,0.627093,0.936179,0.655794,0.712543,0.678589,0.644450,0.653439,0.630671,0.604154,4
214,Took trash out but bag ripped,"[0.66132396, 0.62646234, 0.6291745, 0.6289149,...",0.661324,0.626462,0.629174,0.628915,0.686035,0.689649,0.714929,0.706982,0.651598,0.948998,0.572808,10
220,The drill was too large,"[0.77960414, 0.96567565, 0.7002468, 0.6742349,...",0.779604,0.965676,0.700247,0.674235,0.683938,0.650028,0.644625,0.614323,0.757352,0.633606,0.629470,2
249,The Miter saw was too tall,"[0.68479675, 0.7487134, 0.63537306, 0.91050965...",0.684797,0.748713,0.635373,0.910510,0.682739,0.727754,0.684348,0.662881,0.658608,0.651637,0.618134,4
250,The 12v drills were in an unlabeled cabinet,"[0.69469625, 0.77071685, 0.59575, 0.6648452, 0...",0.694696,0.770717,0.595750,0.664845,0.713237,0.670133,0.665308,0.656184,0.919104,0.616348,0.588390,9
254,Ripped trash bag,"[0.6559895, 0.6101904, 0.6384808, 0.6411876, 0...",0.655990,0.610190,0.638481,0.641188,0.700307,0.696051,0.696083,0.727758,0.650865,1.000000,0.562800,10
259,Clamps out of place,"[0.74643874, 0.715369, 0.6075213, 0.6531729, 0...",0.746439,0.715369,0.607521,0.653173,0.900181,0.674045,0.701735,0.692741,0.690558,0.668823,0.635027,5
266,The miter saw is too tall,"[0.6819933, 0.7475054, 0.63607776, 0.92123413,...",0.681993,0.747505,0.636078,0.921234,0.680939,0.731980,0.678034,0.671341,0.662396,0.647030,0.618561,4
267,Trash bag was ripped,"[0.6731103, 0.64082545, 0.6540079, 0.6467726, ...",0.673110,0.640825,0.654008,0.646773,0.716365,0.695275,0.724760,0.721131,0.657216,0.974074,0.589199,10
268,Drills were too big,"[0.7433954, 0.9281515, 0.69731313, 0.6363407, ...",0.743395,0.928151,0.697313,0.636341,0.701367,0.629318,0.632143,0.623245,0.721943,0.618577,0.616759,2
269,Lost clamps,"[0.7051837, 0.6681346, 0.6117401, 0.65526044, ...",0.705184,0.668135,0.611740,0.655260,0.909213,0.675669,0.702022,0.708892,0.703125,0.699412,0.609624,5
286,The chuck for the lathe was tightened too much,"[0.9211866, 0.8057959, 0.61435616, 0.62569594,...",0.921187,0.805796,0.614356,0.625696,0.736807,0.647422,0.625459,0.625109,0.709731,0.620118,0.635035,1
290,lathe chuck was too tight,"[0.93225443, 0.80179805, 0.6313929, 0.61149955...",0.932254,0.801798,0.631393,0.611500,0.710319,0.631360,0.618652,0.611984,0.695256,0.622509,0.619738,1
295,garbage bag ripped,"[0.65321356, 0.61830807, 0.6417494, 0.6378683,...",0.653214,0.618308,0.641749,0.637868,0.698348,0.687357,0.696528,0.713777,0.646975,0.983451,0.574871,10
301,Ripped garbage bag,"[0.6572418, 0.6128895, 0.6348448, 0.6361241, 0...",0.657242,0.612890,0.634845,0.636124,0.702813,0.695601,0.692495,0.723017,0.651790,0.989480,0.569137,10
303,Someone bumped into her,"[0.6348177, 0.6499023, 0.6004541, 0.6723578, 0...",0.634818,0.649902,0.600454,0.672358,0.727994,0.703276,0.910152,0.628600,0.674638,0.699084,0.629565,7
304,Ripped trash bag,"[0.6559895, 0.6101904, 0.6384808, 0.6411876, 0...",0.655990,0.610190,0.638481,0.641188,0.700307,0.696051,0.696083,0.727758,0.650865,1.000000,0.562800,10
312,ripped trashbag,"[0.66373926, 0.6290784, 0.6432038, 0.65558356,...",0.663739,0.629078,0.643204,0.655584,0.717479,0.688160,0.712954,0.737407,0.671263,0.980663,0.569051,10
320,Trash bag ripped,"[0.65364015, 0.6159076, 0.6438184, 0.6431225, ...",0.653640,0.615908,0.643818,0.643122,0.697710,0.688772,0.701068,0.720318,0.645353,0.994154,0.567680,10
328,Miter Saw,"[0.6610374, 0.69269073, 0.65142155, 0.9156239,...",0.661037,0.692691,0.651422,0.915624,0.716830,0.768491,0.709330,0.700799,0.724349,0.685152,0.615717,4
329,Clamps,"[0.71715754, 0.67120254, 0.6190368, 0.66463554...",0.717158,0.671203,0.619037,0.664636,0.924693,0.669514,0.707808,0.692819,0.673748,0.675291,0.631905,5
331,Trash bag ripped,"[0.65364015, 0.6159076, 0.6438184, 0.6431225, ...",0.653640,0.615908,0.643818,0.643122,0.697710,0.688772,0.701068,0.720318,0.645353,0.994154,0.567680,10
337,The bag of scraps ripped,"[0.6555634, 0.63270694, 0.6267792, 0.6394708, ...",0.655563,0.632707,0.626779,0.639471,0.749644,0.737760,0.677062,0.788661,0.661198,0.919342,0.583110,10
340,Miter saw slightly too tall,"[0.6915839, 0.7384812, 0.63733655, 0.9192374, ...",0.691584,0.738481,0.637337,0.919237,0.673188,0.710234,0.702310,0.644794,0.666489,0.632276,0.615467,4
349,The trash bag ripped when taking it out,"[0.65088004, 0.63389826, 0.60491264, 0.6181679...",0.650880,0.633898,0.604913,0.618168,0.693332,0.694080,0.675252,0.706047,0.651915,0.936407,0.569693,10
356,ripped trash bag,"[0.6559895, 0.6101904, 0.6384808, 0.6411876, 0...",0.655990,0.610190,0.638481,0.641188,0.700307,0.696051,0.696083,0.727758,0.650865,1.000000,0.562800,10
359,Misplaced clamps,"[0.71742076, 0.6901809, 0.6063218, 0.6576372, ...",0.717421,0.690181,0.606322,0.657637,0.916441,0.677095,0.705291,0.709015,0.711812,0.693872,0.624487,5
365,Somebody bumped into him,"[0.63925004, 0.66271526, 0.61598456, 0.6792539...",0.639250,0.662715,0.615985,0.679254,0.725074,0.716437,0.922859,0.644726,0.679665,0.704225,0.637074,7
398,Trash bag was torn,"[0.67276335, 0.64441377, 0.6636173, 0.6302071,...",0.672763,0.644414,0.663617,0.630207,0.714648,0.692363,0.721005,0.706531,0.653639,0.947665,0.598647,10

In [77]:
# now, get cohens kappa score for the filtered data
ground_truths = all_scores_expanded_filtered["Consensus code"].tolist()
predictions = all_scores_expanded_filtered[["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]].idxmax(axis=1).tolist()
# convert predictions from strings to ints
predictions = [int(x) for x in predictions]
kappa = cohen_kappa_score(ground_truths, predictions, labels=[1,2,3,4,5,6,7,8,9,10,11], weights=None, sample_weight=None)
print(kappa)

1.0